<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Commands\**" />
      <EmbeddedResource Remove="Commands\**" />
      <None Remove="Commands\**" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp-firstpass">
          <HintPath>..\..\..\OneDrive\Documents\ExiledDependencies\Assembly-CSharp-firstpass.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.API">
          <HintPath>..\..\..\AppData\Roaming\SCP Secret Laboratory\PluginAPI\plugins\global\dependencies\Exiled.API.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CreditTags">
          <HintPath>..\..\AppData\Roaming\EXILED\Plugins\Exiled.CreditTags.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CustomItems">
          <HintPath>..\..\..\AppData\Roaming\EXILED\Plugins\Exiled.CustomItems.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.CustomRoles">
          <HintPath>..\..\AppData\Roaming\EXILED\Plugins\Exiled.CustomRoles.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Events">
          <HintPath>..\..\..\AppData\Roaming\EXILED\Plugins\Exiled.Events.dll</HintPath>
        </Reference>
        <Reference Include="Exiled.Permissions">
          <HintPath>..\..\AppData\Roaming\EXILED\Plugins\Exiled.Permissions.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.CSharp" />
        <Reference Include="Mirror">
          <HintPath>..\..\..\OneDrive\Documents\ExiledDependencies\Mirror.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
          <HintPath>..\..\..\OneDrive\Documents\ExiledDependencies\UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
          <HintPath>..\..\..\OneDrive\Documents\ExiledDependencies\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
          <HintPath>..\..\..\OneDrive\Documents\ExiledDependencies\UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ExMod.Exiled" Version="9.5.0" />
    </ItemGroup>

</Project>
